language: node_js
node_js:
  - "6"
branches:
  only: master
script:
  - npm run build:docs
after_script:
  - git config user.name "Dafrok"
  - git config user.email "o.o@mug.dog"
  - git add .
  - git commit -m "Travis build docs"
  - git push origin master --force --quiet "https://${GITHUB_TOKEN}@github.com/Dafrok/vue-baidu-map.git"
